### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by webdev03** [The-Forum-Participators/the-forum-participators.github.io#16]
MIT? GPL? Apache? Unlicense?

**Comment by ILOVETOMAKESTUFF** [comment]
I'll look into it...

**Comment by ILOVETOMAKESTUFF** [comment]
Where do you view licenses?

**Comment by Jbear-Scratch** [comment]
What am doing, here, i have no idea how to use this ;-;

**Comment by ILOVETOMAKESTUFF** [comment]
@Jbear-Scratch You are here to discuss which license to use.

**Comment by Autofirejm** [comment]
do MIT for now, we can always change it

**Comment by ILOVETOMAKESTUFF** [comment]
@Autofirejm Okay, but we will keep this open, just in case salad wants to change it

**Comment by ILOVETOMAKESTUFF** [comment]
Alright, is it good?

**Comment by webdev03** [comment]
> do MIT for now, we can always change it

Once we license code, we can't change it, the code will always be licensed with that

**Comment by ILOVETOMAKESTUFF** [comment]
> > do MIT for now, we can always change it
> 
> Once we license code, we can't change it, the code will always be licensed with that

Okay, then topic closed
