### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [The-Forum-Participators/the-forum-participators.github.io#18]
What was the `404.html` file for? How will you access it?

**Comment by Autofirejm** [comment]
https://the-forum-participators.github.io/e
https://the-forum-participators.github.io/skdhsoishilahos/ajshkahdlfiauhsoidb
https://the-forum-participators.github.io/a/a/a/a
these all return 404s
the ones with the /'s have broken CSS

**Comment by Mbrick2** [comment]
Seems to be solved. @ILOVETOMAKESTUFF

**Comment by ILOVETOMAKESTUFF** [comment]
@Autofirejm But why would anyone type that? Just click the link...

**Comment by webdev03** [comment]
> the ones with the /'s have broken CSS

Just use / to direct the browser to root directory

**Comment by Mbrick2** [comment]
[Fixed broken CSS](https://the-forum-participators.github.io/a/a)
