### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [The-Forum-Participators/the-forum-participators.github.io#21]
https://github.com/The-Forum-Participators/the-forum-participators.github.io/blob/e7e52120b3f2e9f63b162975d39aaf82da2896dd/style.css#L72
I feel like this color option would have to be reconsidered. First, it makes the navbar look bad, and it makes the members' list links look bad. (it's for visited links)

**Comment by ILOVETOMAKESTUFF** [comment]
If anything, I could change it back

**Comment by AutoTheKat** [comment]
What about adding special classes? E.G. “navbar” and “real link”

**Comment by webdev03** [comment]
> What about adding special classes? E.G. “navbar” and “real link”

CSS selectors can do that. No need for adding special classes.

**Comment by ILOVETOMAKESTUFF** [comment]
Links are back to black, no need for this anymore.
