### ISSUE TITLE
Could someone change my rank to community manager on the members list 

### ISSUE THREAD

**Issue by Jbear-Scratch** [The-Forum-Participators/the-forum-participators.github.io#24]
^

**Comment by Jbear-Scratch** [comment]
I dont know how to use this so i dont know how to label or assign people lol

**Comment by ILOVETOMAKESTUFF** [comment]
I'll see what I can do.

**Comment by webdev03** [comment]
I wrote the code for the members list, I will still help maintain it if it is possible for me to do so, I can do this soon.

**Comment by ILOVETOMAKESTUFF** [comment]
Done

**Comment by webdev03** [comment]
How is it done? I haven't done it yet.

**Comment by Jbear-Scratch** [comment]
Uh
