### ISSUE TITLE
Which color should the NavBar be?

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [The-Forum-Participators/the-forum-participators.github.io#4]
https://github.com/The-Forum-Participators/the-forum-participators.github.io/blob/e9eb1af624962ad2ef68de04d390ce7dfedee031/style.css#L6
Is it already good or should I change it?

**Comment by Autofirejm** [comment]
hmm... i'm not sure, maybe transparent or blurred background?

**Comment by Autofirejm** [comment]
also you are needed in the SA studio

**Comment by ILOVETOMAKESTUFF** [comment]
> hmm... i'm not sure, maybe transparent or blurred background?

No, I meant for the navbar:
![image](https://user-images.githubusercontent.com/97681427/156695470-04cbd39b-af2f-445d-8061-c56bf2275550.png)

**Comment by Autofirejm** [comment]
> > hmm... i'm not sure, maybe transparent or blurred background?
> 
> No, I meant for the navbar: ![image](https://user-images.githubusercontent.com/97681427/156695470-04cbd39b-af2f-445d-8061-c56bf2275550.png)

yes, that's what i mean

**Comment by ILOVETOMAKESTUFF** [comment]
I think i'll just keep it like this for now. If anyone whats me to change it, they could tell me or you or you could just comment on the discussion for the changes/updates
